name: "Teste"

on: push

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: echo
        run: |
          DATETIME=$(date +"%Y-%m-%dT%H:%M:%S")
          echo "Teste as ${DATETIME}"
